name: 📦 GHN Checker

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  packages: read

jobs:
  execute:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/skinexa/bank-approver:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
      env:
        NODE_ENV: production
    steps:
      - name: 📙 Create env file
        uses: actions/github-script@v6
        with:
          script: |
            const { writeFileSync } = require('fs');
            const secrets = ${{toJson(secrets)}};
            writeFileSync(`/app/.env`, secrets['ENV']);

      - name: 🔎 Approving bank transactions
        run: node -e "require('/app/main.js').ghnChecker()"